branches:
  only:
    - main

language: cpp

script-anchors:
  - &script-Makefiles
    - cmake --version

    - git clone --branch=4.2.0 --depth=1 --single-branch
      -- https://github.com/juce-framework/JUCE.git ci/tmp/JUCE-4.2.0
    - git clone --branch=4.3.1 --depth=1 --single-branch
      -- https://github.com/juce-framework/JUCE.git ci/tmp/JUCE-4.3.1
    - git clone --branch=5.0.0 --depth=1 --single-branch
      -- https://github.com/juce-framework/JUCE.git ci/tmp/JUCE-5.0.0
    - git clone --branch=5.2.1 --depth=1 --single-branch
      -- https://github.com/juce-framework/JUCE.git ci/tmp/JUCE-5.2.1
    - git clone --branch=5.3.1 --depth=1 --single-branch
      -- https://github.com/juce-framework/JUCE.git ci/tmp/JUCE-5.3.1
    - git clone --branch=5.4.3 --depth=1 --single-branch
      -- https://github.com/juce-framework/JUCE.git ci/tmp/JUCE-5.4.3
    - git clone --branch=5.4.7 --depth=1 --single-branch
      -- https://github.com/juce-framework/JUCE.git ci/tmp/JUCE-5.4.7
    - git clone --branch=6.0.1 --depth=1 --single-branch
      -- https://github.com/juce-framework/JUCE.git ci/tmp/JUCE-6.0.1

    - mkdir ${TRAVIS_BUILD_DIR}/Debug_build
    - mkdir ${TRAVIS_BUILD_DIR}/Release_build

    # Configure and build FRUT with JUCE 4.2.0
    - cd ${TRAVIS_BUILD_DIR}/Debug_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0"
    - cmake --build . -- -j4
    - cd ${TRAVIS_BUILD_DIR}/Release_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0"

    # Configure and build FRUT with JUCE 4.3.1
    - cd ${TRAVIS_BUILD_DIR}/Debug_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1"
    - cmake --build . -- -j4
    - cd ${TRAVIS_BUILD_DIR}/Release_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1"

    # Configure and build FRUT with JUCE 5.0.0
    - cd ${TRAVIS_BUILD_DIR}/Debug_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0"
    - cmake --build . -- -j4
    - cd ${TRAVIS_BUILD_DIR}/Release_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0"

    # Configure and build FRUT with JUCE 5.2.1
    - cd ${TRAVIS_BUILD_DIR}/Debug_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.1"
    - cmake --build . -- -j4
    - cd ${TRAVIS_BUILD_DIR}/Release_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.1"

    # Configure and build FRUT with JUCE 5.3.1
    - cd ${TRAVIS_BUILD_DIR}/Debug_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.3.1"
    - cmake --build . -- -j4
    - cd ${TRAVIS_BUILD_DIR}/Release_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.3.1"

    # Configure and build FRUT with JUCE 5.4.3
    - cd ${TRAVIS_BUILD_DIR}/Debug_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.4.3"
    - cmake --build . -- -j4
    - cd ${TRAVIS_BUILD_DIR}/Release_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.4.3"

    # Configure and build FRUT with JUCE 5.4.7
    - cd ${TRAVIS_BUILD_DIR}/Debug_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.4.7"
    - cmake --build . -- -j4
    - cd ${TRAVIS_BUILD_DIR}/Release_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.4.7"

    # Configure and build FRUT with JUCE 6.0.1
    - cd ${TRAVIS_BUILD_DIR}/Debug_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-6.0.1"
    - cmake --build . -- -j4
    - cd ${TRAVIS_BUILD_DIR}/Release_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-6.0.1"

    # Build and install FRUT in ./prefix
    - cmake .. -G"${GENERATOR}" -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/prefix"
    - cmake --build . --target install -- -j4

    # Check that generated CMakeLists.txt files are up-to-date
    - cd ${TRAVIS_BUILD_DIR}
    - >
      cmake -DJucer2CMake_EXE="prefix/FRUT/bin/Jucer2CMake"
      -P ci/apply-Jucer2CMake-reprojucer-to-test-jucers.cmake
    - >
      cmake -DJUCE_VERSION="4.2.0"
      -DJucer2CMake_EXE="prefix/FRUT/bin/Jucer2CMake"
      -P ci/apply-Jucer2CMake-reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="4.3.1"
      -DJucer2CMake_EXE="prefix/FRUT/bin/Jucer2CMake"
      -P ci/apply-Jucer2CMake-reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="5.0.0"
      -DJucer2CMake_EXE="prefix/FRUT/bin/Jucer2CMake"
      -P ci/apply-Jucer2CMake-reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="5.2.1"
      -DJucer2CMake_EXE="prefix/FRUT/bin/Jucer2CMake"
      -P ci/apply-Jucer2CMake-reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="5.3.1"
      -DJucer2CMake_EXE="prefix/FRUT/bin/Jucer2CMake"
      -P ci/apply-Jucer2CMake-reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="5.4.3"
      -DJucer2CMake_EXE="prefix/FRUT/bin/Jucer2CMake"
      -P ci/apply-Jucer2CMake-reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="5.4.7"
      -DJucer2CMake_EXE="prefix/FRUT/bin/Jucer2CMake"
      -P ci/apply-Jucer2CMake-reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="6.0.1"
      -DJucer2CMake_EXE="prefix/FRUT/bin/Jucer2CMake"
      -P ci/apply-Jucer2CMake-reprojucer-to-JUCE-jucers.cmake
    - git diff --exit-code

    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_build
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_build

    # Configure all JUCE 4.2.0 projects
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_build
    - >
      cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="4.2.0"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_build
    - >
      cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="4.2.0"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"

    # Configure all JUCE 4.3.1 projects
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_build
    - >
      cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="4.3.1"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_build
    - >
      cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="4.3.1"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"

    # Configure all JUCE 5.0.0 projects
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_build
    - >
      cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="5.0.0"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_build
    - >
      cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="5.0.0"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"

    # Configure all JUCE 5.2.1 projects
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_build
    - >
      cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="5.2.1"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_build
    - >
      cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="5.2.1"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"

    # Configure all JUCE 5.3.1 projects
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_build
    - >
      cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="5.3.1"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_build
    - >
      cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="5.3.1"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"

    # Configure all JUCE 5.4.3 projects
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="5.4.3"
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="5.4.3"

    # Configure all JUCE 5.4.7 projects
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="5.4.7"
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="5.4.7"

    # Configure all JUCE 6.0.1 projects
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="6.0.1"
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_build
    - cmake .. -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="6.0.1"

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libasound2-dev
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
            - webkit2gtk-4.0
      env: GENERATOR="Unix Makefiles"
      script: *script-Makefiles

    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libasound2-dev
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
            - webkit2gtk-4.0
      env: GENERATOR="CodeBlocks - Unix Makefiles"
      script: *script-Makefiles

    - os: osx
      env: GENERATOR="Unix Makefiles"
      osx_image: xcode7.3
      script: *script-Makefiles
